#Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M5ODJmZDYyMWJiNDJiMDE0YjE4N2EiLCJpYXQiOjE3NDEyNTk1MTcsImV4cCI6MTc0MTM0NTkxN30.dhNvQdFb94HQki-65biH90afH_aCoDK60pl4LnJxGJ4
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Pedro",
  "age": 20,
  "email": "luis@test.com",
  "password": "HolaMundo01"
}

###
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "test10@test.com",
  "password": "HolaMundo01"
}


######################################################################
POST http://localhost:3001/api/tracks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M5ODJmZDYyMWJiNDJiMDE0YjE4N2EiLCJpYXQiOjE3NDEyNTk1MTcsImV4cCI6MTc0MTM0NTkxN30.dhNvQdFb94HQki-65biH90afH_aCoDK60pl4LnJxGJ4

{
    "dato": "basura",
    "name": "nombre",
    "album": "album",
    "cover": "http://tttt.com",
    "artist": {
        "name": "ric",
        "nickname": "rsurname",
        "nationality": "ES"
    },
    "duration": {
        "start": 1,
        "end": 2
    },
    "mediaId": "507f191e810c19729de860ea"
}

###
POST http://localhost:3001/api/tracks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M5ODJmZDYyMWJiNDJiMDE0YjE4N2EiLCJpYXQiOjE3NDEyNTk1MTcsImV4cCI6MTc0MTM0NTkxN30.dhNvQdFb94HQki-65biH90afH_aCoDK60pl4LnJxGJ4

{
    "name": "Track Válido",
    "album": "Álbum Válido",
    "cover": "http://ejemplo.com/cover-valid.jpg",
    "artist": {
        "name": "Artista Válido",
        "nickname": "ValidNick",
        "nationality": "ES"
    },
    "duration": {
        "start": 0,
        "end": 300
    },
    "mediaId": "507f191e810c19729de860ea"
}

###
GET http://localhost:3001/api/tracks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M5ODJmZDYyMWJiNDJiMDE0YjE4N2EiLCJpYXQiOjE3NDEyNTk1MTcsImV4cCI6MTc0MTM0NTkxN30.dhNvQdFb94HQki-65biH90afH_aCoDK60pl4LnJxGJ4

###
GET http://localhost:3001/api/tracks/67add625fc9687edcaea7c96 HTTP/1.1
Authorization: Bearer <TU_JWT_TOKEN>

###
GET http://localhost:3001/api/tracks HTTP/1.1
POST http://localhost:3001/api/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="image"; filename="img-piñata.jpg"
Content-Type: image/jpg

< ./img-piñata.jpg
--Boundary--

###
### STORAGE: OBTENER TODOS LOS ARCHIVOS
GET http://localhost:3001/api/storage HTTP/1.1

######################################################################
### RUTAS DE USUARIOS (ACTUALIZAR ROL)
######################################################################
PUT http://localhost:3001/api/users/role HTTP/1.1
Content-Type: application/json
Authorization: Bearer <TU_ADMIN_JWT_TOKEN>

{
  "id": "67c6e4aea7e70ab54d5f5be2",
  "role": "admin"
}

######################################################################

