@baseUrl = http://localhost:3001

### 1. Registro de usuario
POST {{baseUrl}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Luis",
  "age": 22,
  "email": "luis.ferrer@live.u-tad.com",
  "password": "Password123"
}

###
@tokenFromRegister = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U4ODI5MmU5YmQ2YTdkZmNhNzA0OGUiLCJpYXQiOjE3NDMyOTEwMjYsImV4cCI6MTc0MzM3NzQyNn0.TVMynTfc7Z9UXj9NL0QO7HslxUd6efsz4_wsxKZMcek

### 2. Validación de email (Registro)
POST {{baseUrl}}/api/users/validate-email HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenFromRegister}}

{
  "code": "884097"
}

### 3. Login de usuario
POST {{baseUrl}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "luis.ferrer@live.u-tad.com",
  "password": "Password123"
}

###
@tokenFromLogin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U4ODI5MmU5YmQ2YTdkZmNhNzA0OGUiLCJpYXQiOjE3NDMyOTExMDgsImV4cCI6MTc0MzM3NzUwOH0.2EEplVo3m_7ds77Vur5sS91Z_P5LXr83JZ0d2LU0Z18
@userId = 67e88292e9bd6a7dfca7048e

### 4. On boarding – Datos personales
PATCH {{baseUrl}}/api/users/onboarding/personal HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenFromLogin}}

{
  "name": "Luis Updated",
  "lastName": "Smith",
  "nif": "12345678A"
}

### 5. On boarding – Datos de la compañía
PATCH {{baseUrl}}/api/users/onboarding/company HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenFromLogin}}

{
  "companyName": "Acme Corp",
  "cif": "A12345678",
  "address": "123 Main Street"
}

### 6. Actualizar logo
PATCH {{baseUrl}}/api/users/logo HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundary
Authorization: Bearer {{tokenFromLogin}}

--Boundary
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpg

< ./image.jpg
--Boundary--

### 7. Recuperar contraseña – Enviar código de recuperación
POST {{baseUrl}}/api/users/recover-password-code HTTP/1.1
Content-Type: application/json

{
  "email": "luis.ferrer@live.u-tad.com",
  "currentPassword": "Password123"
}

### 8. Cambiar contraseña – Usando el código recibido
POST {{baseUrl}}/api/users/change-password HTTP/1.1
Content-Type: application/json

{
  "email": "luis.ferrer@live.u-tad.com",
  "recoveryCode": "346553",
  "newPassword": "NewPass456"
}

### 9. Invitación de usuario
POST {{baseUrl}}/api/users/invite HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenFromLogin}}

{
  "email": "bob@example.com"
}

### 10. Enviar Email (prueba de mails)
POST {{baseUrl}}/api/mail HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{tokenFromLogin}}

{
  "subject": "Test Email",
  "text": "Este es un email enviado desde Nodemailer con OAuth2.",
  "to": "luis.ferrer@live.u-tad.com",
  "from": "luisferrer2002@gmail.com"
}
